# Generated by Django 4.1.7 on 2023-03-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree_menu", "0002_item_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="url",
            field=models.URLField(editable=False, max_length=300),
        ),
    ]
