# Generated by Django 4.1.7 on 2023-03-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree_menu", "0003_alter_item_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="slug",
            field=models.SlugField(max_length=255, unique=True, verbose_name="Item slug"),
        ),
    ]
