# Generated by Django 4.1.7 on 2023-03-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tree_menu", "0004_alter_item_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="url",
            field=models.URLField(blank=True, editable=False, max_length=300),
        ),
    ]
